name: test
on:
  push:
    branches: none
  workflow_dispatch:
    branches: none
jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install iverilog
        shell: bash
        run: sudo apt-get update && sudo apt-get install -y ghdl

      # Set Python up and install cocotb
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python packages
        shell: bash
        run: pip install -r test/requirements.txt

      - name: Run tests
        run: |
          cd test
          python3 top.py
          # make will return success even if the test fails, so check for failure in the results.xml
          ! grep failure results.xml

      - name: Test Summary
        uses: test-summary/action@v2.3
        with:
          paths: "test/sim_build/results.xml"
        if: always()

      - name: upload ghw
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-ghw
          path: |
            test/sim_build/top.ghw
            test/sim_build/results.xml
